### PR TITLE
fixed linebreaks and ampersands

### PR DESCRIPTION
**Pull request by Himura2la**
I tried to display my equation like this (but a bit more heavy)

https://mathembed.com/latex?inputText=%5Cbegin%7Bpmatrix%7D%0Ay_0%20%26%20z_c%20%26%20x_0%0A%5Cend%7Bpmatrix%7D

and failed.

Here's the fix, please merge and publish to mathembed.com

### CODE REVIEW

**Comment by codeOfRobin** [comment]
Huh, I'm not quite so sure how this works 🤔. But I'm not one to argue with regex magic, so go ahead!

**Comment by Himura2la** [comment]
I didn't catch it also, but StackExchance, you know... xD
Thanks for merging, I hope this won't break anything.
Now it requires ES6 for multiline strings

**Comment by codeOfRobin** [comment]
It's deployed automatically on the mathembed.com server, in case you want to check. Also, thank you for contributing! 

PS: May I know where you're using mathembed? I'd love to place your work as part of an "examples" section in the README!

**Comment by Himura2la** [comment]
I used it on [Medium](medium.com). Although looks like I can't control the embed area size there, which is quite sad

image

**Comment by codeOfRobin** [comment]
Ah, that's sadly a limitation of the oembed spec. You have to provide a set height and width. I wonder if you could set it dynamically 🤔  (will have to double check if the spec has changed)

**Comment by codeOfRobin** [comment]
If it helps, we could reduce the default height to fit most common use cases

**Comment by Himura2la** [comment]
If you control the the size of an embed area, it's better to make it fit the content. 
If you really need this, for now the height of my tallest equation is 250px

**Comment by Himura2la** [comment]
About the PR, it was a very quick fix, consifer moving the code here https://github.com/codeOfRobin/MathEmbed/blob/master/app.js#L51

When it's where it is now, the processing and markup are mixed, whis is a bad architecture

**Comment by codeOfRobin** [comment]
> When it's where it is now, the processing and markup are mixed, whis is a bad architecture

Yes, definitely 😄 . I wrote this as a quick hack over a couple of days, will definitely consider cleaning it up.

As for the size considerations, check out section 2.3.4.4 on https://oembed.com . I wonder if there's a way to compute an estimated height from the embed URL?

**Comment by Himura2la** [comment]
> Example: http://img.catbo.at/oembed.json?url=http://img.catbo.at/3fb93c1b7891aedb18aa41fb325cbc92e82e58a1.jpg&maxwidth=200&maxheight=45&format=json

?

It will solve the problem if we just let the user control the width/height values via the GET parameters

**Pull request merged**
